apiVersion: v1
kind: Namespace
metadata:
  name: engine
spec:
  selector:
    matchLabels:
      name: engine
  template:
    metadata:
      labels:
        name: engine
    spec:
      containers:
        - name: engine-fuzz
          image: tensorprogramming/engine
          imagePullPolicy: IfNotPresent
