[package]
name = "fuzz"
version = "0.1.0"
authors = ["tensor-programming <tensordeveloper@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vault = {path = "../../vault"}
crypto = {path = "../../crypto"}
random = {path = "../../random"}
primitives = {path = "../../primitives"}

[profile.release]
overflow-checks = true
panic = "abort"

[profile.dev]
overflow-checks = true
panic = "abort"

[workspace]