[package]
name = "snapshot"
version = "0.1.0"
authors = ["tensor-programming <tensordeveloper@gmail.com>"]
edition = "2018"
readme = "README.md"

[dependencies]
# error handling
thiserror = "1.0"
anyhow = "1.0"

# crypto
sodiumoxide = "0.2"

# file system
dirs = "3.0"

crypto = {path = "../crypto"}
random = {path = "../random"}

